fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\SonataUser\User
  group:
    group_class: App\Entity\SonataUser\Group
    group_manager: sonata.user.orm.group_manager
  service:
    user_manager: sonata.user.orm.user_manager
  from_email:
    address: '%env(MAILER_USER)%'
    sender_name: '%env(MAILER_USER)%'